### PR TITLE
testish

### PR DESCRIPTION
**Pull request by x9136**
Check

### CODE REVIEW

**Comment by lorrding** [comment]
Well, it returns an *Error: Resource not accessible by integration*.

But it successfully detected the issues on the icons though I don't know what issue because as a failed developer that I am, I forgot to echo the type of issue 😢

Anyway, the error may be caused because github-actions have different rights depending on who made the PR ?

**Comment by x9136** [comment]
> Anyway, the error may be caused because github-actions have different rights depending on who made the PR ?

I can't help you with that. Maybe someone else can or you can figure it out yourself.

If the checks were successful, I would like to see how the bot handles additional commits.

**Comment by lorrding** [comment]
I'm currently trying to rewrite the workflow using JS 'cause I'm more familiar with it, and I can use libs like JSDOM to properly parse the SVG file as an XML document and do wayyy more than just looking at a string of text.

Current objectif are:
- Build a set of rules
- Detect issues in svg files
- Review SVG files with every issue found
- Launch workflow again after contributors posted something like "ready".

Or we could see if we can change the type of PR to a draft if any issue is found and simply wait for the contributor to flag it as ready for review and then run the checking again.

**Comment by x9136** [comment]
> Or we could see if we can change the type of PR to a draft if any issue is found and simply wait for the contributor to flag it as ready for review and then run the checking again.

I'm not sure which trigger is possible and more appropriate. In theory, you should wait for new commits. Check what is in those commits. If the commits have new svgs, that is, without renaming the old ones too, then the bot checks the icons in that commit and writes a review.

It feels like if we do something wrong here, there will be clutter, so I suggest finalizing this after the first version if you wish. For most cases it will be enough to do a review 1 time after a PR is published.

**Pull request closed without merging**
